### ISSUE TITLE
Question about github-octicons

### ISSUE THREAD

**Issue by XhmikosR** [github/government.github.com#188] opened 2013-11-13 08:55 UTC
How were github-octicons generated? I ask because the .eot file doesn't work on IE8, but if I regenerate the font files from the .ttf one using [fontsquirrel](http://www.fontsquirrel.com/tools/webfont-generator) it works fine.

**Comment by benbalter** [comment] 2013-11-14 15:38
@XhmikosR the Octicon font isn't fully released into the wild yet, so expect some hiccups. 

/cc @cameronmcefee, in case you're interested in investigating. May be an older build. Believe it was pulled straight from the repo.

**Closed as completed by benbalter** 2013-11-14 15:38 UTC

**Comment by XhmikosR** [comment] 2013-11-14 15:42
Well, GitHub has dropped support for IE < 9. But this site still supports it as far as I can tell.

Anyway, since this isn't open source, I don't think I can do anything. I already reported everything I know.

**Comment by cameronmcefee** [comment] 2013-11-14 16:24
Hi @XhmikosR,

Thanks for the report. I'll investigate this one and see if we can get it working properly soon.

**Comment by XhmikosR** [comment] 2013-11-14 16:33
Thanks, let me know your findings.

BTW, I tried using FontForge to fix the font name vs public name but I couldn't make it work right. I did notice, however, some inconsistencies in the font names which might cause this issue.

**Comment by cameronmcefee** [comment] 2013-11-14 17:46
Should be resolved [here](https://github.com/github/government.github.com/pull/191). The cause of the issue is the omission of the `?` from the eot url. If you want to get deep in the details, check out [this article](http://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/).

Thus far this has been omitted from the octicons stylesheet because the `?` causes issues with Sprockets. Since this project isn't using Sprockets it's not a big deal here, but we'll need to look further into it to be able to support IE8 on projects that _do_ use Sprockets.

While I was at it, I updated Octicons which includes some font name conflicts that were discovered a few weeks ago. So far they haven't caused an issue in production, but it can't hurt to get everything consistent.

**Comment by XhmikosR** [comment] 2013-11-14 17:48
The `?` isn't the cause because as I mention in that patch I had already fixed it. (refs https://github.com/github/government.github.com/commit/db16a2940fb070c037b549a72102f92b75caad08)

The cause is the font name differences like I mentioned [above](https://github.com/github/government.github.com/issues/188#issuecomment-28498812) :)

EDIT: No idea where that branch is based on though. It doesn't include any of my previously merged icon fixes...

**Comment by cameronmcefee** [comment] 2013-11-14 18:04
You're correct, my changes were based on an old branch. I'm fixing that as we speak.

**Comment by cameronmcefee** [comment] 2013-11-14 18:19
Alright, new pull in #192

**Comment by XhmikosR** [comment] 2013-11-14 18:21
This issue should have been closed when @cameronmcefee patches were merged, though. It's a real issue.

I'll try the new branch @cameronmcefee and let you know.
