### ISSUE TITLE
Run scripts not working

### ISSUE THREAD

**Issue by suriyaa** [github/government.github.com#320] opened 2014-09-22 14:44 UTC
Hello everybody, :smile:

I need your help!

I tried today to **run over *Git Shell**\* `script/bootstrap` and `script/server` on my Laptop but it doesn't work. :unamused:

So it looks when `script/bootstrap` is finished:
![screenshot 2014-09-22 16 34 27](https://cloud.githubusercontent.com/assets/5073946/4357941/6857327a-4266-11e4-84bc-ee27ff18cb4f.png)

So it looks when `script/server` is finished:
![screenshot 2014-09-22 16 35 06](https://cloud.githubusercontent.com/assets/5073946/4357942/6969b368-4266-11e4-899d-0c3e68ea7625.png)

Thanks for your help.

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

_(PS: I install "nokogiri" and "bundle" and it's still not work.)_

**Comment by benbalter** [comment] 2016-02-26 15:08
@SuriyaaKudoIsc are you still having trouble?

**Comment by suriyaa** [comment] 2016-02-26 15:26
@benbalter 

---

Yes.

I use Windows 10 (german edition) now but I got the same issue.

---

I run:

``` bash
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Suriyaa\Documents\GitHub> git clone https://github.com/github/government.github.com.git
Cloning into 'government.github.com'...
remote: Counting objects: 6231, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 6231 (delta 11), reused 0 (delta 0), pack-reused 6177
Receiving objects: 100% (6231/6231), 19.67 MiB | 5.04 MiB/s, done.
Resolving deltas: 100% (3016/3016), done.
Checking connectivity... done.
C:\Users\Suriyaa\Documents\GitHub> cd government.github.com
C:\Users\Suriyaa\Documents\GitHub\government.github.com [gh-pages]> script/bootstrap
script/bootstrap : Die Benennung "script/bootstrap" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die
Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ script/bootstrap
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (script/bootstrap:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: Der Befehl script/bootstrap wurde nicht gefunden. Er ist jedoch am aktuellen Ort vorhanden. Windows PowerShell lädt Befehle nicht standardmäßig vom aktuellen Ort. Wenn Sie diesem Befehl vertrauen, geben Sie stattdessen ".\script/bootstrap" ein. Weitere Informationen erhalten Sie unter "get-help about_Command_Precedence".
C:\Users\Suriyaa\Documents\GitHub\government.github.com [gh-pages]> cd script
C:\Users\Suriyaa\Documents\GitHub\government.github.com\script [gh-pages]> bootstrap
bootstrap : Die Benennung "bootstrap" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des
Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ bootstrap
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bootstrap:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: Der Befehl bootstrap wurde nicht gefunden. Er ist jedoch am aktuellen Ort vorhanden. Windows PowerShell lädt Befehle nicht standardmäßig vom aktuellen Ort. Wenn Sie diesem Befehl vertrauen, geben Sie stattdessen ".\bootstrap" ein. Weitere Informationen erhalten Sie unter "get-help about_Command_Precedence".
```

![screenshot 2016-02-26 16 24 35](https://cloud.githubusercontent.com/assets/5073946/13356431/81c4297c-dca5-11e5-8b30-9eae19f3402e.png)

---

> Running the commands `script/bootstrap` and `script/server` on Windows doesn't work. :unamused:

**Comment by XhmikosR** [comment] 2016-02-29 21:42
Everything is fine on Windows regarding these issues.

The only issue you will hit is the `server` or `jekyll server` one due to the symlink'ed _sass/bootstrap file.

**Comment by suriyaa** [comment] 2016-03-01 16:27
I tried to run `jekyll server` command directly in CMD:

``` bash
C:\Users\Suriyaa\Documents\GitHub\government.github.com>jekyll server
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/resolver.rb:347:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-avatar (>= 0) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `each'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `verify_gemfile_dependencies_are_found!'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/resolver.rb:198:in `start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/resolver.rb:182:in `resolve'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/jekyll-3.1.1/lib/jekyll/plugin_manager.rb:33:in `require_from_bundler'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/jekyll-3.1.1/bin/jekyll:9:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/bin/jekyll:23:in `load'
        from C:/RailsInstaller/Ruby2.1.0/bin/jekyll:23:in `<main>'

C:\Users\Suriyaa\Documents\GitHub\government.github.com>
```

**Comment by XhmikosR** [comment] 2016-03-01 16:33
The problem is on your side. Ruby 2.1.0 isn't the latest either.

Anyway, @benbalter, you should close this.

**Comment by suriyaa** [comment] 2016-03-30 07:34
@XhmikosR :+1:

**Closed as completed** 2016-03-30 07:34 UTC
